config/routes.rb
Projects::Application.routes.draw do
  devise_for :installs

  resources :items

  devise_for :users

 root :to => "Items#index"

end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  has_one :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.xml
#  before_filter :authenticate_user!, :except=>[:index]
  before_filter :authenticate_user!, :except=>[:show,:index]

#    
#    @items_ = Item.all


  def index
     @items=[]
     if user_signed_in?
       @items = Item.where(:user_id => current_user.id)
     else
       puts "not signed in"
     end

     if @items.empty?
       puts "@items is empty"
     else

      respond_to do |format|
       format.html # index.html.erb
       format.xml  { render :xml => @items }
      end
     end
  end
  # GET /items/1
  # GET /items/1.xml
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @item }
    end
  end

  # GET /items/new
  # GET /items/new.xml
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.xml
  def create
    @item = Item.new(params[:item])
    @item.user_id = current_user
 
    respond_to do |format|
      if @item.save
        format.html { redirect_to(@item, :notice => 'Item was successfully created.') }
        format.xml  { render :xml => @item, :status => :created, :location => @item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.xml
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to(@item, :notice => 'Item was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.xml
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to(items_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :make %><br />
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model_name %><br />
    <%= f.text_field :model_name %>
  </div>
  <div class="field">
    <%= f.label :model_number %><br />
    <%= f.text_field :model_number %>
  </div>
  <div class="field">
    <%= f.label :serial_number %><br />
    <%= f.text_field :serial_number %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :purchase_price %><br />
    <%= f.text_field :purchase_price %>
  </div>
  <div class="field">
    <%= f.label :purchase_date %><br />
    <%= f.date_select :purchase_date %>
  </div>
  <div class="field">
    <%= f.label :place_purchased %><br />
    <%= f.text_field :place_purchased %>
  </div>
  <div class="field">
    <%= f.label :mfg_warranty_expires %><br />
    <%= f.date_select :mfg_warranty_expires %>
  </div>
  <div class="field">
    <%= f.label :ext_warranty_expires %><br />
    <%= f.date_select :ext_warranty_expires %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/_sortable.html.erb
<% content_for :javascript do %>

<script type="text/javascript">
 jQuery.noConflict();
 jQuery(document).ready(function()
 {
  jQuery("#itemTable").tablesorter({
	widgets: ["zebra"], 
	sortList: [[0,0]]
	});
 }
);
</script>

<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<% render 'sortable' %>

<h1>Your items</h1>

<div id="itemTable_Container">

<table id="itemTable" class="tablesorter">
<thead>
  <tr>
    <th>Make</th>
    <th>Model name</th>
    <th>Model number</th>
    <th>Serial number</th>
    <th>Category</th>
    <th>Purchase price</th>
    <th>Purchase date</th>
    <th>Place purchased</th>
    <th>Mfg warranty expires</th>
    <th>Ext warranty expires</th>
    <th>Description</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>

<tbody>
<% @items.each do |item| %>
  <tr>
    <td><%= item.make %></td>
    <td><%= item.model_name %></td>
    <td><%= item.model_number %></td>
    <td><%= item.serial_number %></td>
    <td><%= item.category %></td>
    <td><%= item.purchase_price %></td>
    <td><%= item.purchase_date %></td>
    <td><%= item.place_purchased %></td>
    <td><%= item.mfg_warranty_expires %></td>
    <td><%= item.ext_warranty_expires %></td>
    <td><%= item.description %></td>
    <td><%= item.user_id %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</tbody>
</table>

</div itemTable_Container>

<br />

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>


<table border="3">
<tr>
<td><b>Make</b></td>
<td><b>Model Name</b></td>
<td><b>Model Number</b></td>
<td><b>Serial Number</b></td>
<td><b>Category</b></td>
<td><b>Purchase Price</b></td>
<td><b>Purchase Date</b></td>
<td><b>Place Purchased</b></td>
<td><b>Mfg. Warranty Expiry Date</b></td>
<td><b>Ext. Warranty Expiry Date</b></td>
<td><b>Description</b></td>
<td><b>User</b></td>
</tr>
<tr>
<td><%= @item.make %></td>
<td><%= @item.model_name %></td>
<td><%= @item.model_number %></td>
<td><%= @item.serial_number %></td>
<td><%= @item.category %></td>
<td><%= @item.purchase_price %></td>
<td><%= @item.purchase_date %></td>
<td><%= @item.place_purchased %></td>
<td><%= @item.mfg_warranty_expires %></td>
<td><%= @item.ext_warranty_expires %></td>
<td><%= @item.description %></td>
<td><%= @item.user_id %></td>
</tr>
</table>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/_header.html.erb
<head>
  <title>Projects</title>
  <%= stylesheet_link_tag "screen.css", "scaffold.css", "sortable.css", "custom.css" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "jquery-rails.js", "jquery.tablesorter.js", "application.js" %>
  <%= csrf_meta_tag %>

  <%= yield :javascript %>

  <div id="header" class="span-24 header">
  <div image>
  <img src="images/house2.jpg" width=100>

  <nav class="round">
    <ul>
    <% if user_signed_in? %>
      <li>Signed in as <%= current_user.email %>
      <li>Not you? <%= link_to "Sign out", destroy_user_session_path %>
    <% else %>
      <li><%=link_to "Sign up", new_user_registration_path %>
      <li><%=link_to "Sign in", new_user_session_path %>
    <% end %>
    </ul>
  </nav>

  </div>


        <hr />

</head>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/header' %>

<body>

<div class="container">
  <%= yield %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

</div>

</body>
</html>